language: java
sudo: false
jdk:
- oraclejdk8

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

install:
- true

before_script:
 - "echo $JAVA_OPTS"
 - "export JAVA_OPTS=-Xmx512m"

script:
- mvn clean install

cache:
  directories:
  - $HOME/.m2

env:
- TERM=dumb

after_success:
- mvn clean test jacoco:report coveralls:report

